// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class T2userfluxtestAddClient1Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void t2userfluxtestAddClient1() {
    // Test name: t2-userflux-testAddClient-1
    // Step # | name | target | value
    // 1 | open | https://opensource-demo.orangehrmlive.com/web/index.php/auth/login | 
    driver.get("https://opensource-demo.orangehrmlive.com/web/index.php/auth/login");
    // 2 | setWindowSize | 602x615 | 
    driver.manage().window().setSize(new Dimension(602, 615));
    // 3 | type | name=password | admin123
    driver.findElement(By.name("password")).sendKeys("admin123");
    // 4 | type | name=username | Admin
    driver.findElement(By.name("username")).sendKeys("Admin");
    // 5 | click | css=.oxd-button | 
    driver.findElement(By.cssSelector(".oxd-button")).click();
    // 6 | click | css=.bi-list | 
    driver.findElement(By.cssSelector(".bi-list")).click();
    // 7 | click | linkText=Time | 
    driver.findElement(By.linkText("Time")).click();
    // 8 | click | css=.oxd-topbar-body-nav-tab:nth-child(4) > .oxd-topbar-body-nav-tab-item | 
    driver.findElement(By.cssSelector(".oxd-topbar-body-nav-tab:nth-child(4) > .oxd-topbar-body-nav-tab-item")).click();
    // 9 | click | css=.oxd-dropdown-menu > li:nth-child(1) | 
    driver.findElement(By.cssSelector(".oxd-dropdown-menu > li:nth-child(1)")).click();
    // 10 | click | css=.oxd-button | 
    driver.findElement(By.cssSelector(".oxd-button")).click();
    // 11 | click | xpath=//div[2]/input | 
    driver.findElement(By.xpath("//div[2]/input")).click();
    // 12 | type | css=.oxd-input--focus | Customer3
    driver.findElement(By.cssSelector(".oxd-input--focus")).sendKeys("Customer3");
    // 13 | click | css=.oxd-textarea | 
    driver.findElement(By.cssSelector(".oxd-textarea")).click();
    // 14 | type | css=.oxd-textarea | Customer 3
    driver.findElement(By.cssSelector(".oxd-textarea")).sendKeys("Customer 3");
    // 15 | click | css=.oxd-button--secondary | 
    driver.findElement(By.cssSelector(".oxd-button--secondary")).click();
    // 16 | click | css=.oxd-userdropdown-img | 
    driver.findElement(By.cssSelector(".oxd-userdropdown-img")).click();
    // 17 | click | linkText=Logout | 
    driver.findElement(By.linkText("Logout")).click();
    // 18 | type | name=password | admin123
    driver.findElement(By.name("password")).sendKeys("admin123");
    // 19 | type | name=username | Admin
    driver.findElement(By.name("username")).sendKeys("Admin");
  }
}
