/*
 * AUTHOR: ENZO SALATINO PICOLI
 * VERSION: 2025-11-10
 * Desc: Teste de sistema para testar o fluxo de usuario dentro do servidor de testes do Orange,
 * o teste é executado usando o driver do firefox, devido como o roteiro foi escrito, e para 
 * instalar o driver foi nescessario adicionar um container dedicado para instalar o firefox pois
 * o codespaces falha ao fazer fetch do driver. O roteiro de teste foi montado usando a extensão 
 * Selenium IDE para o Firefox, e a solução usando container foi bolada com assistencia de 
 * inteligencia artificial.
 */

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.firefox.FirefoxOptions;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
import java.time.Duration;

public class T2userFluxaddClientTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  
//GPT
 @Before
public void setUp() {
    System.setProperty("webdriver.gecko.driver", "/usr/local/bin/geckodriver"); // <-- caminho real
    FirefoxOptions fo = new FirefoxOptions();
    fo.addArguments("-headless");
    fo.setBinary("/usr/bin/firefox");
    driver = new FirefoxDriver(fo);
    driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(5));
}

//GPT
  @After
  public void tearDown() {
    if (driver != null) driver.quit();         // evita NPE se o driver não subir
  }

//SELENIUM
  @Test
  public void t2userfluxaddClient() {
    // Test name: t2-userflux-addClient
    // Step # | name | target | value
    // 1 | open | /web/index.php/auth/login | 
    driver.get("https://opensource-demo.orangehrmlive.com/web/index.php/auth/login");
    // 2 | setWindowSize | 739x616 | 
    driver.manage().window().setSize(new Dimension(739, 616));
    // 3 | waitForElementVisible | css=.orangehrm-login-slot-wrapper | 500
    {
      WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(5));
      wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector(".orangehrm-login-slot-wrapper")));
    }
    // 4 | type | name=password | admin123
    driver.findElement(By.name("password")).sendKeys("admin123");
    // 5 | type | name=username | Admin
    driver.findElement(By.name("username")).sendKeys("Admin");
    // 6 | click | xpath=//div[@id='app']/div/div/div/div/div[2]/div[2]/form/div[3]/button | 
    driver.findElement(By.xpath("//div[@id=\'app\']/div/div/div/div/div[2]/div[2]/form/div[3]/button")).click();
    // 7 | waitForElementVisible | css=.oxd-topbar-header | 500
    {
      WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(5));
      wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector(".oxd-topbar-header")));
    }
    // 8 | click | css=.bi-list | 
    driver.findElement(By.cssSelector(".bi-list")).click();
    // 8.1 | waitForElementVisible | css=.oxd-main-menu-item-wrapper:nth-child(4) .oxd-text | 500
    {
      WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(5));
      wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector(".oxd-main-menu-item-wrapper:nth-child(4) .oxd-text")));
    }
    // 9 | click | css=.oxd-main-menu-item-wrapper:nth-child(4) .oxd-text | BREAKPOINT
    driver.findElement(By.cssSelector(".oxd-main-menu-item-wrapper:nth-child(4) .oxd-text")).click();
    // 10 | waitForElementVisible | css=.oxd-topbar-body | 500
    {
      WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(5));
      wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector(".oxd-topbar-body")));
    }
    // 11 | click | xpath=//div[@id='app']/div/div/header/div[2]/nav/ul/li[4]/span | 
    driver.findElement(By.xpath("//div[@id=\'app\']/div/div/header/div[2]/nav/ul/li[4]/span")).click();
    // 12 | click | css=.oxd-dropdown-menu > li:nth-child(1) | 
    driver.findElement(By.cssSelector(".oxd-dropdown-menu > li:nth-child(1)")).click();
    // 13 | waitForElementVisible | css=.oxd-layout-context | 500
    {
      WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(5));
      wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector(".oxd-layout-context")));
    }
    // 14 | click | css=.bi-plus | 
    driver.findElement(By.cssSelector(".bi-plus")).click();
    // 15 | waitForElementVisible | css=.oxd-layout-context | 500
    {
      WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(5));
      wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector(".oxd-layout-context")));
    }
    // 16 | click | xpath=//div[@id='app']/div/div[2]/div[2]/div/div/form/div/div/div[2]/input | 
    driver.findElement(By.xpath("//div[@id=\'app\']/div/div[2]/div[2]/div/div/form/div/div/div[2]/input")).click();
    // 17 | type | css=.oxd-input--focus | CustomerTest
    driver.findElement(By.cssSelector(".oxd-input--focus")).sendKeys("CustomerTest");
    // 18 | click | xpath=//div[@id='app']/div/div[2]/div[2]/div/div/form/div[2]/div/div[2]/textarea | 
    driver.findElement(By.xpath("//div[@id=\'app\']/div/div[2]/div[2]/div/div/form/div[2]/div/div[2]/textarea")).click();
    // 19 | type | css=.oxd-textarea | teste para o t2 de verival
    driver.findElement(By.cssSelector(".oxd-textarea")).sendKeys("teste para o t2 de verival");
    // 20 | click | css=.oxd-form | 
    driver.findElement(By.cssSelector(".oxd-form")).click();
    // 21 | click | css=.oxd-button--secondary | 
    driver.findElement(By.cssSelector(".oxd-button--secondary")).click();
    // 22 | click | css=.oxd-userdropdown-img | 
    driver.findElement(By.cssSelector(".oxd-userdropdown-img")).click();
    // 23 | click | linkText=Logout | 
    driver.findElement(By.linkText("Logout")).click();
  }
}
